### ISSUE TITLE
How to install `torch_clustering`?

### ISSUE THREAD

**Issue by Nioolek** [Hzzone/TCL#1]
Dear author, thank you for open-source such good work.
When I run the code with command in `README.md`:
```
export CUDA_VISIBLE_DEVICES=0,1,2,3 # use the first 4 GPUs
torchrun --master_port 17675 --nproc_per_node=4 main.py models/tcl/configs/cifar100_90_prer18.yml
```

The error occurs, logs are shown below:
```
Traceback (most recent call last):
  File "/xxx/TCL/main.py", line 23, in <module>
    from models.basic_template import TrainTask
  File "/xxx/TCL/models/__init__.py", line 8, in <module>
    import_models(osp.dirname(__file__), 'models')
  File "/xxx/TCL/utils/model_register.py", line 99, in import_models
    importlib.import_module(lib)
  File "xxx/anaconda3/envs/cu113_torch110/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/xxx/TCL/models/__init__.py", line 8, in <module>
    import_models(osp.dirname(__file__), 'models')
  File "/xxx/TCL/utils/model_register.py", line 99, in import_models
    importlib.import_module(lib)
  File "/xxx/anaconda3/envs/cu113_torch110/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/xxx/TCL/models/basic_template.py", line 19, in <module>
    import torch_clustering
ModuleNotFoundError: No module named 'torch_clustering'
```

I found the package `torch_cluster` from `https://pytorch-geometric.com/whl/torch-1.10.1%2Bcu113.html`
But I think the package `torch_cluster` is not what the code need.
So, how to install `torch_clustering`?
Hope to get your reply

**Comment by Hzzone** [comment]
This project has not used this package, just delete those lines, or clone from https://github.com/Hzzone/torch_clustering

**Comment by Nioolek** [comment]
Thank you foe your reply
